### ISSUE TITLE
The definition of Q and R

### ISSUE THREAD

**Issue by WYL-Projects** [sebdi/lane-detection#2]
Dear author, 
      Did you take the covariance noise Q and R at random, or did you calculate them？
<img width="583" alt="image" src="https://user-images.githubusercontent.com/50573960/188304769-85bf7ab4-dab1-4d0d-8a10-f9ea473490ec.png">

**Comment by sebdi** [comment]
Hi,
The values were obtained by try and error to get a good result. You can regard them as random.
Best
